### ISSUE TITLE
ORF1ab - sgRNA being called

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#17]
At the moment _any_ read with a leader sequence is classified as subgenomic RNA, even those reads which originate from the region around TRS-L. All of these reads should be classified as genomic RNA.

**Comment by mbdabrowska1** [comment]
- [x] Change search_for_sgRNA_ont.py classify_read function to classify ORF1a and ORF1b as gRNA. 
- [x] Restructure the function sligthly to accommodate for fewer if statements.
- [x] Add an example ORF1a classified read to the reads.sam file in tests/ont folder
- [x] Include a truth statement to the test_search_for_sgRNA_ont.py file and changed assert mapped_reads to 24 (from 23, since we added another example to the test).
- [x] Test if search_for_sgRNA_ont.py properly classifies ORF1a as gRNA
- [x] Check if search_for_sgRNA_illumina.py properly classifies ORF1a as gRNA
- [x] Add an example ORF1a to the reads.sam file in tests/illumina
- [x] Include ORF1a to be tested in the test_search_for_sgRNA_illumina.py file
- [x] Check if test_check_start properly classifies illumina ORF1a as gRNA
