### ISSUE TITLE
Fix tests and start implementing more tests for more data types

### ISSUE THREAD

**Issue by mattdmem** [sheffield-bioinformatics-core/periscope#23]

**Comment by mbdabrowska1** [comment]
Fix tests:
tests/ont
- [x] reformat calling of reads.sam file to use test file location by implementing os.path.dirname(__file__). This ensures that pytest doesn't have to be run from within the folder containing the test, but it can be run from anywhere. This helps when running the test from source code editors (confirmed to work from VSC)

tests/illumina
- [x] remove wrong functions from being imported into the illumina tests. Previously a few functions that don't exist in search_for_sgRNA_illumina.py were attempted to be imported into the test (ie. search_reads, classify_reads, find_amplicon).
- [x] reformat calling of reads.sam file to use test file location by implementing os.path.dirname(__file__). This ensures that pytest doesn't have to be run from within the folder containing the test, but it can be run from anywhere. This helps when running the test from source code editors (confirmed to work from VSC)
- [x] fix mapped_reads test by providing the correct number of mapped reads (33 instead of 23)
- [x] move a part of main() function in search_for_sgRNA_illumina.py which assigns orf into a separate function
- [x] write test which checks for a correct orf assignment (current function not working and not used in the original code)
- [x] finish defining truths for each mapping
- [x] restructure test_extact_soft_clipped_bases function to use the original defined truths
- [x] fix discrepancies between the reads.sam file and the asserted truths in the test
