### ISSUE TITLE
sgRNA count is less than gRNA count

### ISSUE THREAD

**Issue by pratibha-kadam** [sheffield-bioinformatics-core/periscope#45]
Hello there,
I have been using Periscope for my Analysis. 
What I have observed is sgRNA count is very les compared to gRNA. According to the theory if the virus is replicating it shall produce more sgRNA than gRNA, isn't it?  
My gRNA is in thousands and sgRNA in points.

Please help me to understand this.
Thanks in advance

**Comment by mbdabrowska1** [comment]
Is this with nanopore or illumina?

**Comment by pratibha-kadam** [comment]
Yes. Its a Nanopore data.

**Comment by mattdmem** [comment]
Hello,

Thanks for your interest in periscope @pratibha-kadam! Sub-genomic RNA is amplified by ARTIC primers through unintended amplification due to primer 1 complementarity to the genomic leader sequence. This unintended amplification is a lot lot less efficient than the actual intended amplification so that is why we see a lot less. This is one reason why we say periscope is best for sample to sample comparisons of sgRNA levels. It's not the absolute amount that matters, it's the relative amounts.

Thanks

Matt

**Comment by pratibha-kadam** [comment]
Thank you @mattdmem😊.It was really helpful.
Can you also clarify on for comparisons of samples we are taking sgRNA:gRNA RPHT towards normalization of transcript for each gene and also cumulative before comparison between samples.
so, is it ok to consider this sgRNA count per gRNA to compare the sgRNA count between the groups??

Thanks and Regards,
Pratibha

**Comment by mattdmem** [comment]
No problem.

RPHT - This is the normalisation method used, it is intended to account for the variability in the amount of sequencing data produced per sample/per run. In the case of RPHT, this is the number of reads per hundred thousand.

You can also normalise the sgRNA to the number of gRNA reads produced from the same amplicon (well it's not really the same amplicon, but same right hand primer). This is sgRPTg - sgRNA reads per thousand gRNA reads. 

More details here: https://github.com/sheffield-bioinformatics-core/periscope#normalisation

Matt
